-- Adicionar colunas para armazenar todos os dados do CSV
ALTER TABLE locatarios_contratos
ADD COLUMN IF NOT EXISTS inquilino_nome VARCHAR(255) NULL AFTER cpf,
ADD COLUMN IF NOT EXISTS tipo_imovel VARCHAR(50) NULL AFTER numero_contrato,
ADD COLUMN IF NOT EXISTS cidade VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS estado VARCHAR(2) NULL,
ADD COLUMN IF NOT EXISTS bairro VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS cep VARCHAR(10) NULL,
ADD COLUMN IF NOT EXISTS endereco VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS numero VARCHAR(20) NULL,
ADD COLUMN IF NOT EXISTS complemento VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS unidade VARCHAR(50) NULL,
ADD COLUMN IF NOT EXISTS empresa_fiscal VARCHAR(255) NULL;

